In [1]:
import pandas as pd
import numpy as np
import joblib
from taxipred.utils.constants import DATA_PATH
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

df = pd.read_csv(DATA_PATH / "cleaned_data.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       925 non-null    float64
 1   Time_of_Day            926 non-null    object
 2   Day_of_Week            925 non-null    object
 3   Passenger_Count        925 non-null    float64
 4   Traffic_Conditions     924 non-null    object
 5   Weather                925 non-null    object
 6   Base_Fare              925 non-null    float64
 7   Per_Km_Rate            926 non-null    float64
 8   Per_Minute_Rate        927 non-null    float64
 9   Trip_Duration_Minutes  924 non-null    float64
 10  Trip_Price             925 non-null    float64
dtypes: float64(7), object(4)
memory usage: 83.8+ KB

In [2]:
is_null = df.isna().sum()

is_null

Trip_Distance_km         49
Time_of_Day              48
Day_of_Week              49
Passenger_Count          49
Traffic_Conditions       50
Weather                  49
Base_Fare                49
Per_Km_Rate              48
Per_Minute_Rate          47
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

### Dropping rows with NaN values in Trip_Price and saving it to a training dataframe. 

Defininf two variabels to test models with, one with all features, one with only the highest features

In [3]:
df_train = df.dropna(subset=["Trip_Price"])

all_features = df_train.drop(columns=["Trip_Price"]).columns.tolist()
high_features = [
    "Trip_Distance_km",
    "Per_Km_Rate",
    "Trip_Duration_Minutes",
    "Per_Minute_Rate"
]

feature_sets = {
    "all_features": all_features,
    "high_features": high_features
}

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 925 entries, 0 to 973
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       876 non-null    float64
 1   Time_of_Day            878 non-null    object
 2   Day_of_Week            880 non-null    object
 3   Passenger_Count        878 non-null    float64
 4   Traffic_Conditions     875 non-null    object
 5   Weather                880 non-null    object
 6   Base_Fare              882 non-null    float64
 7   Per_Km_Rate            883 non-null    float64
 8   Per_Minute_Rate        879 non-null    float64
 9   Trip_Duration_Minutes  879 non-null    float64
 10  Trip_Price             925 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.7+ KB

## 0. Divide dataset into X (features) and y (target)

In [5]:
X, y = df_train[high_features], df_train["Trip_Price"]

X.sample(5)

     Trip_Distance_km  Per_Km_Rate  Trip_Duration_Minutes  Per_Minute_Rate
716             41.01         1.80                  16.56             0.42
636              7.25         1.73                  19.51             0.17
934              5.06         1.22                  83.63             0.48
793              3.68         1.16                  79.58             0.44
539              7.57         1.70                 103.80             0.23

In [6]:
X.isna().sum()

Trip_Distance_km         49
Per_Km_Rate              42
Trip_Duration_Minutes    46
Per_Minute_Rate          46
dtype: int64

## 1. Split the data into train | test

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
    )

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((619, 4), (306, 4), (619,), (306,))

## 2. Preprocessing

### Replacing NaN-values for numerical and categorical features

In [8]:
num_cols = X_train.select_dtypes(include="number").columns
cat_cols = X_train.select_dtypes(include="object").columns

Changing NaN values on numerical features to Median and categorical columns to "Missing"

In [9]:
num_imputer = SimpleImputer(strategy="mean")

X_train[num_cols] = num_imputer.fit_transform(X_train[num_cols])
X_test[num_cols] = num_imputer.transform(X_test[num_cols])

#cat_imputer = SimpleImputer(strategy="constant", fill_value="Missing")

#X_train[cat_cols] = cat_imputer.fit_transform(X_train[cat_cols])
#X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

### Changing categorical columns to numerical with .get_dummies

In [10]:
X_train = pd.get_dummies(X_train, columns=cat_cols, drop_first=True)
X_test = pd.get_dummies(X_test, columns=cat_cols, drop_first=True)

X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

# Testing different ML-models

# LinearRegression

### 2. Preprocessing

Scaling

In [11]:
minmax_scaler = MinMaxScaler()
minmax_scaler.fit(X_train)

minmax_scaled_X_train = minmax_scaler.transform(X_train)
minmax_scaled_X_test = minmax_scaler.transform(X_test)

minmax_scaled_X_test[:5]

array([[0.48644887, 0.27333333, 0.06454142, 0.225     ],
       [0.16741896, 0.02      , 0.29788346, 0.95      ],
       [0.30118999, 0.66666667, 0.13639927, 0.8       ],
       [0.85514977, 0.02666667, 1.0001742 , 0.1       ],
       [0.55211325, 0.2       , 0.65124989, 0.95      ]])

In [12]:
minmax_scaled_X_train.max(), minmax_scaled_X_train.min(), minmax_scaled_X_test.max(), minmax_scaled_X_test.min()

(np.float64(1.0000000000000002),
 np.float64(0.0),
 np.float64(1.0001742008535845),
 np.float64(-0.00041034058268362567))

### 3. Training

In [13]:
model = LinearRegression()
model.fit(minmax_scaled_X_train, y_train)

model.intercept_, model.coef_

(np.float64(-22.365650889252528),
 array([59.77916421, 35.70642609, 32.65375306, 24.72008004]))

### 4. Prediction

In [14]:
y_pred_linear = model.predict(minmax_scaled_X_test)
y_pred_linear[:10]

array([24.14315011, 21.56773196, 43.67353096, 64.83810863, 62.53033236,
       65.85935327, 63.6625667 , 31.07729389, 38.02084146, 84.89244811])

### 5. Evaluation

In [15]:
mae_linear = mean_absolute_error(y_test, y_pred_linear)
mse_linear = mean_squared_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mse_linear)

mae_linear, mse_linear, rmse_linear

(6.427741673808306, 68.16399259342138, np.float64(8.256148774908395))

### <mark> LinearRegression gave us RMSE = 6.97  </mark>

## RandomForestRegressor

### 3. Training

In [16]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

### 4. Prediction

In [17]:
y_pred_rf = rf.predict(X_test)
y_pred_rf[:10]

array([29.694977, 29.238726, 36.008308, 50.473124, 65.265433, 72.518629,
       44.567358, 34.779164, 28.282276, 76.686478])

### 5. Evaluation

In [18]:
mae = mean_absolute_error(y_test, y_pred_rf)
mse = mean_squared_error(y_test, y_pred_rf)
rmse = np.sqrt(mse)

mae, mse, rmse

(4.673977117647053, 42.704983137334764, np.float64(6.534904983037991))

### <mark> RandomForestRegression gave us RMSE = 4.5 </mark>

### Feature importance

In [19]:
rf.feature_importances_

array([0.49686069, 0.24065733, 0.17216864, 0.09031334])

Feature importance sorted on most important to least important:

In [20]:
feature_importance = pd.DataFrame([X.columns, rf.feature_importances_]).T
feature_importance.columns = ["feature", "importance"]
feature_importance = feature_importance.sort_values(by="importance", ascending=False)
feature_importance

                 feature importance
0       Trip_Distance_km   0.496861
1            Per_Km_Rate   0.240657
2  Trip_Duration_Minutes   0.172169
3        Per_Minute_Rate   0.090313

# KNN

### 2. Scaling dataset

In [21]:
scaler = StandardScaler()
scaler.fit(X_train)

scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train.min(), scaled_X_train.max(), scaled_X_test.min(), scaled_X_test.max()

(np.float64(-1.8238856674299226),
 np.float64(1.8843047494215737),
 np.float64(-1.822608974665598),
 np.float64(1.8843047494215737))

### 3. Training

In [22]:
model = KNeighborsRegressor(n_neighbors=5)
model.fit(scaled_X_train, y_train)

KNeighborsRegressor()

### 4. Predicting

In [23]:
y_pred_knn = model.predict(scaled_X_test)
y_pred_knn[:10]

array([35.1262 , 30.03424, 33.20704, 52.26052, 62.83702, 67.88118,
       49.32832, 34.26424, 30.96076, 81.74166])

### 5. Evaluation

In [24]:
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)

mae_knn, mse_knn, rmse_knn

(4.945804836601307, 44.04662576421176, np.float64(6.636763199347387))

### <mark> KNN gave us RMSE = 5.12 </mark>

# Conclusion

- LinearRegression gave us RMSE = 6.97
- RandomForestRegression gave us RMSE = 4.5
- KNN gave us RMSE = 5.12

RandomForest gave us the best result.

# Training model

In [25]:
rf.fit(X, y)

RandomForestRegressor(random_state=42)

In [26]:
# joblib.dump(rf, MODEL_PATH / "taxi_price_prediction.joblib", compress=("xz", 3), protocol=5)